// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DccOperationsCommand.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

/**
 * Protobuf type {@code modes3.protobuf.DccOperationsCommand}
 */
public  final class DccOperationsCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:modes3.protobuf.DccOperationsCommand)
    DccOperationsCommandOrBuilder {
  // Use DccOperationsCommand.newBuilder() to construct.
  private DccOperationsCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DccOperationsCommand() {
    dccOperations_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private DccOperationsCommand(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            dccOperations_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommandOuterClass.internal_static_modes3_protobuf_DccOperationsCommand_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommandOuterClass.internal_static_modes3_protobuf_DccOperationsCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand.class, hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand.Builder.class);
  }

  public static final int DCCOPERATIONS_FIELD_NUMBER = 1;
  private int dccOperations_;
  /**
   * <code>optional .modes3.protobuf.DccOperations dccOperations = 1;</code>
   */
  public int getDccOperationsValue() {
    return dccOperations_;
  }
  /**
   * <code>optional .modes3.protobuf.DccOperations dccOperations = 1;</code>
   */
  public hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations getDccOperations() {
    hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations result = hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations.valueOf(dccOperations_);
    return result == null ? hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dccOperations_ != hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations.NORMAL_OPERATIONS.getNumber()) {
      output.writeEnum(1, dccOperations_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dccOperations_ != hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations.NORMAL_OPERATIONS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, dccOperations_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand)) {
      return super.equals(obj);
    }
    hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand other = (hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand) obj;

    boolean result = true;
    result = result && dccOperations_ == other.dccOperations_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + DCCOPERATIONS_FIELD_NUMBER;
    hash = (53 * hash) + dccOperations_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code modes3.protobuf.DccOperationsCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:modes3.protobuf.DccOperationsCommand)
      hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommandOuterClass.internal_static_modes3_protobuf_DccOperationsCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommandOuterClass.internal_static_modes3_protobuf_DccOperationsCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand.class, hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand.Builder.class);
    }

    // Construct using hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dccOperations_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommandOuterClass.internal_static_modes3_protobuf_DccOperationsCommand_descriptor;
    }

    public hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand getDefaultInstanceForType() {
      return hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand.getDefaultInstance();
    }

    public hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand build() {
      hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand buildPartial() {
      hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand result = new hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand(this);
      result.dccOperations_ = dccOperations_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand) {
        return mergeFrom((hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand other) {
      if (other == hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand.getDefaultInstance()) return this;
      if (other.dccOperations_ != 0) {
        setDccOperationsValue(other.getDccOperationsValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int dccOperations_ = 0;
    /**
     * <code>optional .modes3.protobuf.DccOperations dccOperations = 1;</code>
     */
    public int getDccOperationsValue() {
      return dccOperations_;
    }
    /**
     * <code>optional .modes3.protobuf.DccOperations dccOperations = 1;</code>
     */
    public Builder setDccOperationsValue(int value) {
      dccOperations_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .modes3.protobuf.DccOperations dccOperations = 1;</code>
     */
    public hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations getDccOperations() {
      hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations result = hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations.valueOf(dccOperations_);
      return result == null ? hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .modes3.protobuf.DccOperations dccOperations = 1;</code>
     */
    public Builder setDccOperations(hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      dccOperations_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .modes3.protobuf.DccOperations dccOperations = 1;</code>
     */
    public Builder clearDccOperations() {
      
      dccOperations_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:modes3.protobuf.DccOperationsCommand)
  }

  // @@protoc_insertion_point(class_scope:modes3.protobuf.DccOperationsCommand)
  private static final hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand();
  }

  public static hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DccOperationsCommand>
      PARSER = new com.google.protobuf.AbstractParser<DccOperationsCommand>() {
    public DccOperationsCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DccOperationsCommand(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DccOperationsCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DccOperationsCommand> getParserForType() {
    return PARSER;
  }

  public hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

