// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DccOperationsState.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public interface DccOperationsStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:modes3.protobuf.DccOperationsState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .modes3.protobuf.DccOperations dccOperations = 1;</code>
   */
  int getDccOperationsValue();
  /**
   * <code>optional .modes3.protobuf.DccOperations dccOperations = 1;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperations getDccOperations();
}
