// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

/**
 * Protobuf enum {@code modes3.protobuf.DccOperations}
 */
public enum DccOperations
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NORMAL_OPERATIONS = 0;</code>
   */
  NORMAL_OPERATIONS(0),
  /**
   * <code>STOP_ALL_LOCOMOTIVES = 1;</code>
   */
  STOP_ALL_LOCOMOTIVES(1),
  /**
   * <code>STOP_OPERATIONS = 2;</code>
   */
  STOP_OPERATIONS(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NORMAL_OPERATIONS = 0;</code>
   */
  public static final int NORMAL_OPERATIONS_VALUE = 0;
  /**
   * <code>STOP_ALL_LOCOMOTIVES = 1;</code>
   */
  public static final int STOP_ALL_LOCOMOTIVES_VALUE = 1;
  /**
   * <code>STOP_OPERATIONS = 2;</code>
   */
  public static final int STOP_OPERATIONS_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DccOperations valueOf(int value) {
    return forNumber(value);
  }

  public static DccOperations forNumber(int value) {
    switch (value) {
      case 0: return NORMAL_OPERATIONS;
      case 1: return STOP_ALL_LOCOMOTIVES;
      case 2: return STOP_OPERATIONS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DccOperations>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DccOperations> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DccOperations>() {
          public DccOperations findValueByNumber(int number) {
            return DccOperations.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final DccOperations[] VALUES = values();

  public static DccOperations valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DccOperations(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:modes3.protobuf.DccOperations)
}

