// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public final class Enums {
  private Enums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Enums.proto\022\017modes3.protobuf*U\n\rDccOpe" +
      "rations\022\025\n\021NORMAL_OPERATIONS\020\000\022\030\n\024STOP_A" +
      "LL_LOCOMOTIVES\020\001\022\023\n\017STOP_OPERATIONS\020\002*\253\004" +
      "\n\013MessageType\022\010\n\004NULL\020\000\022\023\n\017SEGMENT_COMMA" +
      "ND\020\001\022\021\n\rSEGMENT_STATE\020\002\022\031\n\025TRAIN_CURRENT" +
      "_SEGMENT\020\003\022\027\n\023TRAIN_CURRENT_SPEED\020\004\022\033\n\027T" +
      "RAIN_DIRECTION_COMMAND\020\005\022\031\n\025TRAIN_REFERE" +
      "NCE_SPEED\020\007\022!\n\035TRAIN_REFERENCE_SPEED_COM" +
      "MAND\020\010\022\023\n\017TURNOUT_COMMAND\020\t\022\021\n\rTURNOUT_S" +
      "TATE\020\n\022\025\n\021SEGMENT_OCCUPANCY\020\013\022\026\n\022YAKINDU",
      "_RELEASE_TO\020\014\022\025\n\021YAKINDU_CAN_GO_TO\020\r\022\030\n\024" +
      "YAKINDU_CANNOT_GO_TO\020\016\022\026\n\022YAKINDU_RESERV" +
      "E_TO\020\017\022\035\n\031TURNOUT_REFERENCE_COMMAND\020\020\022\033\n" +
      "\027TURNOUT_REFERENCE_STATE\020\021\022\032\n\026TRAIN_FUNC" +
      "TION_COMMAND\020\022\022\030\n\024TRAIN_FUNCTION_STATE\020\023" +
      "\022\032\n\026DCC_OPERATIONS_COMMAND\020\024\022\030\n\024DCC_OPER" +
      "ATIONS_STATE\020\025\022\023\n\017SEND_ALL_STATUS\020\026*.\n\021S" +
      "egmentStateValue\022\014\n\010DISABLED\020\000\022\013\n\007ENABLE" +
      "D\020\001*0\n\023TrainDirectionValue\022\013\n\007FORWARD\020\000\022" +
      "\014\n\010BACKWARD\020\001*0\n\021TurnoutStateValue\022\014\n\010ST",
      "RAIGHT\020\000\022\r\n\tDIVERGENT\020\001*%\n\022TrainFunction" +
      "Value\022\007\n\003OFF\020\000\022\006\n\002ON\020\001*/\n\025SegmentOccupan" +
      "cyValue\022\010\n\004FREE\020\000\022\014\n\010OCCUPIED\020\001*Y\n\032Yakin" +
      "duConnectionDirection\022\006\n\002CW\020\000\022\007\n\003CCW\020\001\022\t" +
      "\n\005Y_TOP\020\002\022\017\n\013Y_DIVERGENT\020\003\022\016\n\nY_STRAIGHT" +
      "\020\004B0\n,hu.bme.mit.inf.modes3.messaging.mm" +
      "s.messagesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
