// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:modes3.protobuf.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .modes3.protobuf.MessageType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .modes3.protobuf.MessageType type = 1;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.MessageType getType();

  /**
   * <code>optional .modes3.protobuf.SegmentCommand segmentCommand = 2;</code>
   */
  boolean hasSegmentCommand();
  /**
   * <code>optional .modes3.protobuf.SegmentCommand segmentCommand = 2;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentCommand getSegmentCommand();
  /**
   * <code>optional .modes3.protobuf.SegmentCommand segmentCommand = 2;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentCommandOrBuilder getSegmentCommandOrBuilder();

  /**
   * <code>optional .modes3.protobuf.SegmentState segmentState = 3;</code>
   */
  boolean hasSegmentState();
  /**
   * <code>optional .modes3.protobuf.SegmentState segmentState = 3;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentState getSegmentState();
  /**
   * <code>optional .modes3.protobuf.SegmentState segmentState = 3;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentStateOrBuilder getSegmentStateOrBuilder();

  /**
   * <code>optional .modes3.protobuf.TrainCurrentSegment trainCurrentSegment = 4;</code>
   */
  boolean hasTrainCurrentSegment();
  /**
   * <code>optional .modes3.protobuf.TrainCurrentSegment trainCurrentSegment = 4;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainCurrentSegment getTrainCurrentSegment();
  /**
   * <code>optional .modes3.protobuf.TrainCurrentSegment trainCurrentSegment = 4;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainCurrentSegmentOrBuilder getTrainCurrentSegmentOrBuilder();

  /**
   * <code>optional .modes3.protobuf.TrainCurrentSpeed trainCurrentSpeed = 5;</code>
   */
  boolean hasTrainCurrentSpeed();
  /**
   * <code>optional .modes3.protobuf.TrainCurrentSpeed trainCurrentSpeed = 5;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainCurrentSpeed getTrainCurrentSpeed();
  /**
   * <code>optional .modes3.protobuf.TrainCurrentSpeed trainCurrentSpeed = 5;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainCurrentSpeedOrBuilder getTrainCurrentSpeedOrBuilder();

  /**
   * <code>optional .modes3.protobuf.TrainReferenceSpeed trainReferenceSpeed = 7;</code>
   */
  boolean hasTrainReferenceSpeed();
  /**
   * <code>optional .modes3.protobuf.TrainReferenceSpeed trainReferenceSpeed = 7;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainReferenceSpeed getTrainReferenceSpeed();
  /**
   * <code>optional .modes3.protobuf.TrainReferenceSpeed trainReferenceSpeed = 7;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainReferenceSpeedOrBuilder getTrainReferenceSpeedOrBuilder();

  /**
   * <code>optional .modes3.protobuf.TrainReferenceSpeedCommand trainReferenceSpeedCommand = 8;</code>
   */
  boolean hasTrainReferenceSpeedCommand();
  /**
   * <code>optional .modes3.protobuf.TrainReferenceSpeedCommand trainReferenceSpeedCommand = 8;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainReferenceSpeedCommand getTrainReferenceSpeedCommand();
  /**
   * <code>optional .modes3.protobuf.TrainReferenceSpeedCommand trainReferenceSpeedCommand = 8;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainReferenceSpeedCommandOrBuilder getTrainReferenceSpeedCommandOrBuilder();

  /**
   * <code>optional .modes3.protobuf.TurnoutCommand turnoutCommand = 9;</code>
   */
  boolean hasTurnoutCommand();
  /**
   * <code>optional .modes3.protobuf.TurnoutCommand turnoutCommand = 9;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutCommand getTurnoutCommand();
  /**
   * <code>optional .modes3.protobuf.TurnoutCommand turnoutCommand = 9;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutCommandOrBuilder getTurnoutCommandOrBuilder();

  /**
   * <code>optional .modes3.protobuf.TurnoutState turnoutState = 10;</code>
   */
  boolean hasTurnoutState();
  /**
   * <code>optional .modes3.protobuf.TurnoutState turnoutState = 10;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutState getTurnoutState();
  /**
   * <code>optional .modes3.protobuf.TurnoutState turnoutState = 10;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutStateOrBuilder getTurnoutStateOrBuilder();

  /**
   * <code>optional .modes3.protobuf.SegmentOccupancy segmentOccupancy = 11;</code>
   */
  boolean hasSegmentOccupancy();
  /**
   * <code>optional .modes3.protobuf.SegmentOccupancy segmentOccupancy = 11;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentOccupancy getSegmentOccupancy();
  /**
   * <code>optional .modes3.protobuf.SegmentOccupancy segmentOccupancy = 11;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentOccupancyOrBuilder getSegmentOccupancyOrBuilder();

  /**
   * <code>optional .modes3.protobuf.YakinduReleaseTo yakinduReleaseTo = 12;</code>
   */
  boolean hasYakinduReleaseTo();
  /**
   * <code>optional .modes3.protobuf.YakinduReleaseTo yakinduReleaseTo = 12;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduReleaseTo getYakinduReleaseTo();
  /**
   * <code>optional .modes3.protobuf.YakinduReleaseTo yakinduReleaseTo = 12;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduReleaseToOrBuilder getYakinduReleaseToOrBuilder();

  /**
   * <code>optional .modes3.protobuf.YakinduCanGoTo yakinduCanGoTo = 13;</code>
   */
  boolean hasYakinduCanGoTo();
  /**
   * <code>optional .modes3.protobuf.YakinduCanGoTo yakinduCanGoTo = 13;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduCanGoTo getYakinduCanGoTo();
  /**
   * <code>optional .modes3.protobuf.YakinduCanGoTo yakinduCanGoTo = 13;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduCanGoToOrBuilder getYakinduCanGoToOrBuilder();

  /**
   * <code>optional .modes3.protobuf.YakinduCannotGoTo yakinduCannotGoTo = 14;</code>
   */
  boolean hasYakinduCannotGoTo();
  /**
   * <code>optional .modes3.protobuf.YakinduCannotGoTo yakinduCannotGoTo = 14;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduCannotGoTo getYakinduCannotGoTo();
  /**
   * <code>optional .modes3.protobuf.YakinduCannotGoTo yakinduCannotGoTo = 14;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduCannotGoToOrBuilder getYakinduCannotGoToOrBuilder();

  /**
   * <code>optional .modes3.protobuf.YakinduReserveTo yakinduReserveTo = 15;</code>
   */
  boolean hasYakinduReserveTo();
  /**
   * <code>optional .modes3.protobuf.YakinduReserveTo yakinduReserveTo = 15;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduReserveTo getYakinduReserveTo();
  /**
   * <code>optional .modes3.protobuf.YakinduReserveTo yakinduReserveTo = 15;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduReserveToOrBuilder getYakinduReserveToOrBuilder();

  /**
   * <code>optional .modes3.protobuf.TurnoutReferenceCommand turnoutReferenceCommand = 16;</code>
   */
  boolean hasTurnoutReferenceCommand();
  /**
   * <code>optional .modes3.protobuf.TurnoutReferenceCommand turnoutReferenceCommand = 16;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutReferenceCommand getTurnoutReferenceCommand();
  /**
   * <code>optional .modes3.protobuf.TurnoutReferenceCommand turnoutReferenceCommand = 16;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutReferenceCommandOrBuilder getTurnoutReferenceCommandOrBuilder();

  /**
   * <code>optional .modes3.protobuf.TurnoutReferenceState turnoutReferenceState = 17;</code>
   */
  boolean hasTurnoutReferenceState();
  /**
   * <code>optional .modes3.protobuf.TurnoutReferenceState turnoutReferenceState = 17;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutReferenceState getTurnoutReferenceState();
  /**
   * <code>optional .modes3.protobuf.TurnoutReferenceState turnoutReferenceState = 17;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutReferenceStateOrBuilder getTurnoutReferenceStateOrBuilder();

  /**
   * <code>optional .modes3.protobuf.TrainFunctionCommand trainFunctionCommand = 18;</code>
   */
  boolean hasTrainFunctionCommand();
  /**
   * <code>optional .modes3.protobuf.TrainFunctionCommand trainFunctionCommand = 18;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionCommand getTrainFunctionCommand();
  /**
   * <code>optional .modes3.protobuf.TrainFunctionCommand trainFunctionCommand = 18;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionCommandOrBuilder getTrainFunctionCommandOrBuilder();

  /**
   * <code>optional .modes3.protobuf.TrainFunctionState trainFunctionState = 19;</code>
   */
  boolean hasTrainFunctionState();
  /**
   * <code>optional .modes3.protobuf.TrainFunctionState trainFunctionState = 19;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState getTrainFunctionState();
  /**
   * <code>optional .modes3.protobuf.TrainFunctionState trainFunctionState = 19;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionStateOrBuilder getTrainFunctionStateOrBuilder();

  /**
   * <code>optional .modes3.protobuf.DccOperationsCommand dccOperationsCommand = 20;</code>
   */
  boolean hasDccOperationsCommand();
  /**
   * <code>optional .modes3.protobuf.DccOperationsCommand dccOperationsCommand = 20;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommand getDccOperationsCommand();
  /**
   * <code>optional .modes3.protobuf.DccOperationsCommand dccOperationsCommand = 20;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommandOrBuilder getDccOperationsCommandOrBuilder();

  /**
   * <code>optional .modes3.protobuf.DccOperationsState dccOperationsState = 21;</code>
   */
  boolean hasDccOperationsState();
  /**
   * <code>optional .modes3.protobuf.DccOperationsState dccOperationsState = 21;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsState getDccOperationsState();
  /**
   * <code>optional .modes3.protobuf.DccOperationsState dccOperationsState = 21;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsStateOrBuilder getDccOperationsStateOrBuilder();

  /**
   * <code>optional .modes3.protobuf.SendAllStatus allStatus = 22;</code>
   */
  boolean hasAllStatus();
  /**
   * <code>optional .modes3.protobuf.SendAllStatus allStatus = 22;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.SendAllStatus getAllStatus();
  /**
   * <code>optional .modes3.protobuf.SendAllStatus allStatus = 22;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.SendAllStatusOrBuilder getAllStatusOrBuilder();
}
