// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_modes3_protobuf_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_modes3_protobuf_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\017modes3.protobuf\032\032DccOpe" +
      "rationsCommand.proto\032\030DccOperationsState" +
      ".proto\032\013Enums.proto\032\024SegmentCommand.prot" +
      "o\032\022SegmentState.proto\032\031TrainCurrentSegme" +
      "nt.proto\032\027TrainCurrentSpeed.proto\032\032Train" +
      "FunctionCommand.proto\032\030TrainFunctionStat" +
      "e.proto\032\031TrainReferenceSpeed.proto\032 Trai" +
      "nReferenceSpeedCommand.proto\032\024TurnoutCom" +
      "mand.proto\032\022TurnoutState.proto\032\035TurnoutR" +
      "eferenceCommand.proto\032\033TurnoutReferenceS",
      "tate.proto\032\026SegmentOccupancy.proto\032\026Yaki" +
      "nduReleaseTo.proto\032\024YakinduCanGoTo.proto" +
      "\032\027YakinduCannotGoTo.proto\032\026YakinduReserv" +
      "eTo.proto\032\023SendAllStatus.proto\"\247\n\n\007Messa" +
      "ge\022*\n\004type\030\001 \001(\0162\034.modes3.protobuf.Messa" +
      "geType\0227\n\016segmentCommand\030\002 \001(\0132\037.modes3." +
      "protobuf.SegmentCommand\0223\n\014segmentState\030" +
      "\003 \001(\0132\035.modes3.protobuf.SegmentState\022A\n\023" +
      "trainCurrentSegment\030\004 \001(\0132$.modes3.proto" +
      "buf.TrainCurrentSegment\022=\n\021trainCurrentS",
      "peed\030\005 \001(\0132\".modes3.protobuf.TrainCurren" +
      "tSpeed\022A\n\023trainReferenceSpeed\030\007 \001(\0132$.mo" +
      "des3.protobuf.TrainReferenceSpeed\022O\n\032tra" +
      "inReferenceSpeedCommand\030\010 \001(\0132+.modes3.p" +
      "rotobuf.TrainReferenceSpeedCommand\0227\n\016tu" +
      "rnoutCommand\030\t \001(\0132\037.modes3.protobuf.Tur" +
      "noutCommand\0223\n\014turnoutState\030\n \001(\0132\035.mode" +
      "s3.protobuf.TurnoutState\022;\n\020segmentOccup" +
      "ancy\030\013 \001(\0132!.modes3.protobuf.SegmentOccu" +
      "pancy\022;\n\020yakinduReleaseTo\030\014 \001(\0132!.modes3",
      ".protobuf.YakinduReleaseTo\0227\n\016yakinduCan" +
      "GoTo\030\r \001(\0132\037.modes3.protobuf.YakinduCanG" +
      "oTo\022=\n\021yakinduCannotGoTo\030\016 \001(\0132\".modes3." +
      "protobuf.YakinduCannotGoTo\022;\n\020yakinduRes" +
      "erveTo\030\017 \001(\0132!.modes3.protobuf.YakinduRe" +
      "serveTo\022I\n\027turnoutReferenceCommand\030\020 \001(\013" +
      "2(.modes3.protobuf.TurnoutReferenceComma" +
      "nd\022E\n\025turnoutReferenceState\030\021 \001(\0132&.mode" +
      "s3.protobuf.TurnoutReferenceState\022C\n\024tra" +
      "inFunctionCommand\030\022 \001(\0132%.modes3.protobu",
      "f.TrainFunctionCommand\022?\n\022trainFunctionS" +
      "tate\030\023 \001(\0132#.modes3.protobuf.TrainFuncti" +
      "onState\022C\n\024dccOperationsCommand\030\024 \001(\0132%." +
      "modes3.protobuf.DccOperationsCommand\022?\n\022" +
      "dccOperationsState\030\025 \001(\0132#.modes3.protob" +
      "uf.DccOperationsState\0221\n\tallStatus\030\026 \001(\013" +
      "2\036.modes3.protobuf.SendAllStatusB0\n,hu.b" +
      "me.mit.inf.modes3.messaging.mms.messages" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommandOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsStateOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentCommandOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentStateOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.TrainCurrentSegmentOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.TrainCurrentSpeedOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionCommandOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionStateOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.TrainReferenceSpeedOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.TrainReferenceSpeedCommandOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutCommandOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutStateOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutReferenceCommandOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutReferenceStateOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentOccupancyOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduReleaseToOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduCanGoToOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduCannotGoToOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduReserveToOuterClass.getDescriptor(),
          hu.bme.mit.inf.modes3.messaging.mms.messages.SendAllStatusOuterClass.getDescriptor(),
        }, assigner);
    internal_static_modes3_protobuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_modes3_protobuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_modes3_protobuf_Message_descriptor,
        new java.lang.String[] { "Type", "SegmentCommand", "SegmentState", "TrainCurrentSegment", "TrainCurrentSpeed", "TrainReferenceSpeed", "TrainReferenceSpeedCommand", "TurnoutCommand", "TurnoutState", "SegmentOccupancy", "YakinduReleaseTo", "YakinduCanGoTo", "YakinduCannotGoTo", "YakinduReserveTo", "TurnoutReferenceCommand", "TurnoutReferenceState", "TrainFunctionCommand", "TrainFunctionState", "DccOperationsCommand", "DccOperationsState", "AllStatus", });
    hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsCommandOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.DccOperationsStateOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentCommandOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentStateOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.TrainCurrentSegmentOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.TrainCurrentSpeedOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionCommandOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionStateOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.TrainReferenceSpeedOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.TrainReferenceSpeedCommandOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutCommandOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutStateOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutReferenceCommandOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.TurnoutReferenceStateOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentOccupancyOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduReleaseToOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduCanGoToOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduCannotGoToOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.YakinduReserveToOuterClass.getDescriptor();
    hu.bme.mit.inf.modes3.messaging.mms.messages.SendAllStatusOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
