// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SegmentState.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public interface SegmentStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:modes3.protobuf.SegmentState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 segmentID = 1;</code>
   */
  int getSegmentID();

  /**
   * <code>optional .modes3.protobuf.SegmentStateValue state = 2;</code>
   */
  int getStateValue();
  /**
   * <code>optional .modes3.protobuf.SegmentStateValue state = 2;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.SegmentStateValue getState();
}
