// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendAllStatus.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public interface SendAllStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:modes3.protobuf.SendAllStatus)
    com.google.protobuf.MessageOrBuilder {
}
