// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

/**
 * Protobuf enum {@code modes3.protobuf.TrainFunctionValue}
 */
public enum TrainFunctionValue
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OFF = 0;</code>
   */
  OFF(0),
  /**
   * <code>ON = 1;</code>
   */
  ON(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OFF = 0;</code>
   */
  public static final int OFF_VALUE = 0;
  /**
   * <code>ON = 1;</code>
   */
  public static final int ON_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TrainFunctionValue valueOf(int value) {
    return forNumber(value);
  }

  public static TrainFunctionValue forNumber(int value) {
    switch (value) {
      case 0: return OFF;
      case 1: return ON;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TrainFunctionValue>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TrainFunctionValue> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TrainFunctionValue>() {
          public TrainFunctionValue findValueByNumber(int number) {
            return TrainFunctionValue.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor()
        .getEnumTypes().get(5);
  }

  private static final TrainFunctionValue[] VALUES = values();

  public static TrainFunctionValue valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TrainFunctionValue(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:modes3.protobuf.TrainFunctionValue)
}

