// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrainFunctionCommand.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public interface TrainFunctionCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:modes3.protobuf.TrainFunctionCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 trainID = 1;</code>
   */
  int getTrainID();

  /**
   * <code>optional uint32 functionID = 2;</code>
   */
  int getFunctionID();

  /**
   * <code>optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;</code>
   */
  int getTrainFunctionValueValue();
  /**
   * <code>optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;</code>
   */
  hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue getTrainFunctionValue();
}
