// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrainFunctionCommand.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public final class TrainFunctionCommandOuterClass {
  private TrainFunctionCommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_modes3_protobuf_TrainFunctionCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_modes3_protobuf_TrainFunctionCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032TrainFunctionCommand.proto\022\017modes3.pro" +
      "tobuf\032\013Enums.proto\"|\n\024TrainFunctionComma" +
      "nd\022\017\n\007trainID\030\001 \001(\r\022\022\n\nfunctionID\030\002 \001(\r\022" +
      "?\n\022trainFunctionValue\030\003 \001(\0162#.modes3.pro" +
      "tobuf.TrainFunctionValueB0\n,hu.bme.mit.i" +
      "nf.modes3.messaging.mms.messagesP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor(),
        }, assigner);
    internal_static_modes3_protobuf_TrainFunctionCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_modes3_protobuf_TrainFunctionCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_modes3_protobuf_TrainFunctionCommand_descriptor,
        new java.lang.String[] { "TrainID", "FunctionID", "TrainFunctionValue", });
    hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
