// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrainFunctionState.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

/**
 * Protobuf type {@code modes3.protobuf.TrainFunctionState}
 */
public  final class TrainFunctionState extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:modes3.protobuf.TrainFunctionState)
    TrainFunctionStateOrBuilder {
  // Use TrainFunctionState.newBuilder() to construct.
  private TrainFunctionState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrainFunctionState() {
    trainID_ = 0;
    functionID_ = 0;
    trainFunctionValue_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TrainFunctionState(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            trainID_ = input.readUInt32();
            break;
          }
          case 16: {

            functionID_ = input.readUInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            trainFunctionValue_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionStateOuterClass.internal_static_modes3_protobuf_TrainFunctionState_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionStateOuterClass.internal_static_modes3_protobuf_TrainFunctionState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState.class, hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState.Builder.class);
  }

  public static final int TRAINID_FIELD_NUMBER = 1;
  private int trainID_;
  /**
   * <code>optional uint32 trainID = 1;</code>
   */
  public int getTrainID() {
    return trainID_;
  }

  public static final int FUNCTIONID_FIELD_NUMBER = 2;
  private int functionID_;
  /**
   * <code>optional uint32 functionID = 2;</code>
   */
  public int getFunctionID() {
    return functionID_;
  }

  public static final int TRAINFUNCTIONVALUE_FIELD_NUMBER = 3;
  private int trainFunctionValue_;
  /**
   * <code>optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;</code>
   */
  public int getTrainFunctionValueValue() {
    return trainFunctionValue_;
  }
  /**
   * <code>optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;</code>
   */
  public hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue getTrainFunctionValue() {
    hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue result = hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue.valueOf(trainFunctionValue_);
    return result == null ? hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (trainID_ != 0) {
      output.writeUInt32(1, trainID_);
    }
    if (functionID_ != 0) {
      output.writeUInt32(2, functionID_);
    }
    if (trainFunctionValue_ != hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue.OFF.getNumber()) {
      output.writeEnum(3, trainFunctionValue_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (trainID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, trainID_);
    }
    if (functionID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, functionID_);
    }
    if (trainFunctionValue_ != hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue.OFF.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, trainFunctionValue_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState)) {
      return super.equals(obj);
    }
    hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState other = (hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState) obj;

    boolean result = true;
    result = result && (getTrainID()
        == other.getTrainID());
    result = result && (getFunctionID()
        == other.getFunctionID());
    result = result && trainFunctionValue_ == other.trainFunctionValue_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TRAINID_FIELD_NUMBER;
    hash = (53 * hash) + getTrainID();
    hash = (37 * hash) + FUNCTIONID_FIELD_NUMBER;
    hash = (53 * hash) + getFunctionID();
    hash = (37 * hash) + TRAINFUNCTIONVALUE_FIELD_NUMBER;
    hash = (53 * hash) + trainFunctionValue_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code modes3.protobuf.TrainFunctionState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:modes3.protobuf.TrainFunctionState)
      hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionStateOuterClass.internal_static_modes3_protobuf_TrainFunctionState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionStateOuterClass.internal_static_modes3_protobuf_TrainFunctionState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState.class, hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState.Builder.class);
    }

    // Construct using hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      trainID_ = 0;

      functionID_ = 0;

      trainFunctionValue_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionStateOuterClass.internal_static_modes3_protobuf_TrainFunctionState_descriptor;
    }

    public hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState getDefaultInstanceForType() {
      return hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState.getDefaultInstance();
    }

    public hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState build() {
      hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState buildPartial() {
      hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState result = new hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState(this);
      result.trainID_ = trainID_;
      result.functionID_ = functionID_;
      result.trainFunctionValue_ = trainFunctionValue_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState) {
        return mergeFrom((hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState other) {
      if (other == hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState.getDefaultInstance()) return this;
      if (other.getTrainID() != 0) {
        setTrainID(other.getTrainID());
      }
      if (other.getFunctionID() != 0) {
        setFunctionID(other.getFunctionID());
      }
      if (other.trainFunctionValue_ != 0) {
        setTrainFunctionValueValue(other.getTrainFunctionValueValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int trainID_ ;
    /**
     * <code>optional uint32 trainID = 1;</code>
     */
    public int getTrainID() {
      return trainID_;
    }
    /**
     * <code>optional uint32 trainID = 1;</code>
     */
    public Builder setTrainID(int value) {
      
      trainID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 trainID = 1;</code>
     */
    public Builder clearTrainID() {
      
      trainID_ = 0;
      onChanged();
      return this;
    }

    private int functionID_ ;
    /**
     * <code>optional uint32 functionID = 2;</code>
     */
    public int getFunctionID() {
      return functionID_;
    }
    /**
     * <code>optional uint32 functionID = 2;</code>
     */
    public Builder setFunctionID(int value) {
      
      functionID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 functionID = 2;</code>
     */
    public Builder clearFunctionID() {
      
      functionID_ = 0;
      onChanged();
      return this;
    }

    private int trainFunctionValue_ = 0;
    /**
     * <code>optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;</code>
     */
    public int getTrainFunctionValueValue() {
      return trainFunctionValue_;
    }
    /**
     * <code>optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;</code>
     */
    public Builder setTrainFunctionValueValue(int value) {
      trainFunctionValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;</code>
     */
    public hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue getTrainFunctionValue() {
      hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue result = hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue.valueOf(trainFunctionValue_);
      return result == null ? hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;</code>
     */
    public Builder setTrainFunctionValue(hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      trainFunctionValue_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .modes3.protobuf.TrainFunctionValue trainFunctionValue = 3;</code>
     */
    public Builder clearTrainFunctionValue() {
      
      trainFunctionValue_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:modes3.protobuf.TrainFunctionState)
  }

  // @@protoc_insertion_point(class_scope:modes3.protobuf.TrainFunctionState)
  private static final hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState();
  }

  public static hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrainFunctionState>
      PARSER = new com.google.protobuf.AbstractParser<TrainFunctionState>() {
    public TrainFunctionState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrainFunctionState(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrainFunctionState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrainFunctionState> getParserForType() {
    return PARSER;
  }

  public hu.bme.mit.inf.modes3.messaging.mms.messages.TrainFunctionState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

