// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrainFunctionState.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public final class TrainFunctionStateOuterClass {
  private TrainFunctionStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_modes3_protobuf_TrainFunctionState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_modes3_protobuf_TrainFunctionState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030TrainFunctionState.proto\022\017modes3.proto" +
      "buf\032\013Enums.proto\"z\n\022TrainFunctionState\022\017" +
      "\n\007trainID\030\001 \001(\r\022\022\n\nfunctionID\030\002 \001(\r\022?\n\022t" +
      "rainFunctionValue\030\003 \001(\0162#.modes3.protobu" +
      "f.TrainFunctionValueB0\n,hu.bme.mit.inf.m" +
      "odes3.messaging.mms.messagesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor(),
        }, assigner);
    internal_static_modes3_protobuf_TrainFunctionState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_modes3_protobuf_TrainFunctionState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_modes3_protobuf_TrainFunctionState_descriptor,
        new java.lang.String[] { "TrainID", "FunctionID", "TrainFunctionValue", });
    hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
