// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TurnoutReferenceState.proto

package hu.bme.mit.inf.modes3.messaging.mms.messages;

public final class TurnoutReferenceStateOuterClass {
  private TurnoutReferenceStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_modes3_protobuf_TurnoutReferenceState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_modes3_protobuf_TurnoutReferenceState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033TurnoutReferenceState.proto\022\017modes3.pr" +
      "otobuf\032\013Enums.proto\"]\n\025TurnoutReferenceS" +
      "tate\022\021\n\tturnoutID\030\001 \001(\r\0221\n\005state\030\002 \001(\0162\"" +
      ".modes3.protobuf.TurnoutStateValueB0\n,hu" +
      ".bme.mit.inf.modes3.messaging.mms.messag" +
      "esP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor(),
        }, assigner);
    internal_static_modes3_protobuf_TurnoutReferenceState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_modes3_protobuf_TurnoutReferenceState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_modes3_protobuf_TurnoutReferenceState_descriptor,
        new java.lang.String[] { "TurnoutID", "State", });
    hu.bme.mit.inf.modes3.messaging.mms.messages.Enums.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
