/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Edina' at '2/19/17 12:30 PM' with Gradle 2.14.1
 *
 * @author Edina, @date 2/19/17 12:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
